### PR TITLE
Explore

### PR DESCRIPTION
**Pull request by saketkum11**
- edit comment 
- unfollow, follow
- like and dislike
- bookmark 
- filter ,sort by date

### CODE REVIEW

**Review by mohammadkhizerkhan — APPROVED** [review]
Fix comment UI styling
After clicking update comment close the modal
Try to link profile when I click on profile image or username
Some bug in like

**Review by Pratik1005 — APPROVED** [review]
Bookmark is not working, there is some bug in comment and like feature not working in explore page. Resolve all this before merging.

**Comment by saketkum11** [comment]
> Bookmark is not working, there is some bug in comment and like feature not working in explore page. Resolve all this before merging.

yes changed the code.

**Comment by saketkum11** [comment]
> Fix comment UI styling After clicking update comment close the modal Try to link profile when I click on profile image or username Some bug in like

Yes updated the change .

**Pull request merged**
